spring.application.name=Day3_Darpan_210130107022

spring.datasource.url=jdbc:mysql://localhost:3306/springbootcrud
spring.datasource.username=root
spring.datasource.password=Darpan@930

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true